Repository bigskysoftware/htmx-extensions, pull requests merged in 2024-07, with the labels that each got.

#42 Update index.html
  www/index.html
Labels: documentation

#31 Add trigger 'htmx:sseClose' to sse close event
  src/sse/README.md
  src/sse/sse.js
  src/sse/test/ext/sse.js
Labels: enhancement

#49 docs: update extension example object
  README.md
Labels: documentation

#51 Revise description of class-tools:apply-parent-classes for more clarity.
  src/class-tools/README.md
Labels: documentation

#53 Description: Added .npmignore file to ignore tests file in npm package
  src/ajax-header/.npmignore
  src/bad-extension/.npmignore
  src/class-tools/.npmignore
  src/client-side-templates/.npmignore
  src/debug/.npmignore
  src/disable-element/.npmignore
  src/event-header/.npmignore
  src/head-support/.npmignore
  src/htmx-1-compat/.npmignore
  src/include-vals/.npmignore
  src/json-enc/.npmignore
  src/loading-states/.npmignore
  src/method-override/.npmignore
  src/morphdom-swap/.npmignore
  src/multi-swap/.npmignore
  src/path-deps/.npmignore
  src/path-params/.npmignore
  src/remove-me/.npmignore
  src/response-targets/.npmignore
  src/sse/.npmignore
  src/ws/.npmignore
Labels: bug

#57 Fix hx-vals/hx-vars encoding along json-enc
  src/json-enc/json-enc.js
  src/json-enc/test/ext/json-enc.js
Labels: bug

#66 Remove duplicate safe-nonce description
  www/index.html
Labels: documentation
