Repository bigskysoftware/htmx-extensions, pull requests merged in 2025-03, with the labels that each got.

#150 Correct preload initialisation on forms with fieldsets
  src/preload/preload.js
  src/preload/test/ext/forms.js
Labels: bug

#156 docs: Further update to multi-swap README.md to clarify the use of multi-swap and OOB swaps
  src/multi-swap/README.md
Labels: documentation

#157 Mark preload event listeners as passive
  src/preload/preload.js
Labels: enhancement
